name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build winarg
      working-directory: ./winarg
      run: cargo build
    - name: Quick tests
      working-directory: ./winarg
      run: cargo test --verbose
    - name: Build ./testing
      working-directory: ./testing
      run: cargo build
    - name: Build exhaustive tests
      working-directory: ./testing
      run: cargo test --no-run
      
